#!/usr/bin/env python

import os
import shutil
import argparse
import re
from collections import defaultdict

import vendor.y as y

################################################################################
### Globals
################################################################################

BUILD_DIR: str = "build"
TESTS_DIR: str = "tests"

Y_LIBS: str = "y_meta_libs"
Y_TESTS: str = "y_meta_tests"

CMAKE_TO_IGNORE = {"clean", "help", "rebuild_cache", "edit_cache", "package", "package_source", "build.ninja"}


################################################################################
### Utils
################################################################################


class CMakeTargets:
    def __init__(self) -> None:
        self.binaries = list()
        self.tests = list()

    def contains(self, target_name: str) -> bool:
        return target_name in (self.binaries + self.tests)


def cmake_user_targets(cwd: str) -> CMakeTargets:
    p: y.RunCmdInfo = y.run_cmd(
        ["cmake", "--build", cwd, "--target", "help"],
        verbosity=0,
        permissive=True,
    )
    if p.returncode:
        return CMakeTargets()

    # Extract y.cmake dependencies from CMake cache
    cache_file = os.path.join(cwd, "CMakeCache.txt")
    libs: set[str] = set()
    tests: set[str] = set()

    if not os.path.exists(cache_file):
        return CMakeTargets()

    # Extract libs
    with open(cache_file, "r") as f:
        match = re.search(f"{Y_LIBS}:(.*)=(.+)", f.read(), re.IGNORECASE)
        libs = {lib for lib in match.group(2).strip().split(" ")} if match else set()

    # Extract tests
    with open(cache_file, "r") as f:
        match = re.search(f"{Y_TESTS}:(.*)=(.+)", f.read(), re.IGNORECASE)
        tests = {test for test in match.group(2).strip().split(" ")} if match else set()

    targets = CMakeTargets()
    for line in p.stdout.splitlines():

        # Validate entry
        if ":" not in line:
            continue
        name, _ = line.split(":", 1)
        name = name.strip()
        if targets.contains(name):
            continue

        # Skip meta-targets
        if not name or "/" in name or name in CMAKE_TO_IGNORE:
            continue

        # Skip y.cmake dependencies
        name_lower = name.lower()
        if any(lib.lower() in name_lower or name_lower in lib.lower() for lib in libs):
            continue

        # Append to list and decorate for tests
        if name in tests:
            targets.tests.append(name)
        else:
            targets.binaries.append(name)

    return targets


def norm_target_name(target_name: str) -> list[str]:
    to_print = f" : {target_name}"
    if not target_name or target_name == "all":
        target_name = ""
        to_print = ""
    return [target_name, to_print]


################################################################################
### Config
################################################################################


def config(cwd: str, build_type: str, generator: str, build_tests: bool):
    y.print_header("CONFIG")

    y.run_cmd(
        [
            "cmake",
            "-G",
            generator,
            "../..",
            f"-DCMAKE_BUILD_TYPE={build_type}",
            "-DCMAKE_POLICY_VERSION_MINIMUM=3.10",
            f"-DY_BUILD_TESTS={"ON" if build_tests else "OFF"}",
        ],
        cwd=cwd,
    )


################################################################################
### Build
################################################################################


def build(cwd: str, build_type: str, target_name: str = "all"):
    y.print_header("BUILD")
    target = ["--target", target_name]
    y.run_cmd(["cmake", "--build", ".", "-j", str(os.cpu_count()), "--config", build_type, *target], cwd=cwd)


################################################################################
### Run
################################################################################


def run(target_name: str = "all"):
    target_name, target_name_print = norm_target_name(target_name)
    y.print_header(f"RUNNING{target_name_print}", post="")

    bin_dir: str = os.path.abspath(f"{BUILD_DIR}/bin")
    y.required_folder(bin_dir, info="Bin not executed.")

    for root, dirs, files in os.walk(bin_dir):
        for dirname in dirs:
            if target_name and dirname != target_name:
                continue
            for sub_root, _, files in os.walk(f"{root}/{dirname}"):
                for filename in files:
                    filepath: str = f"{sub_root}/{filename}"

                    if not y.file_is_binary(filepath):
                        continue

                    y.println()

                    p: y.RunCmdInfo = y.run_cmd(
                        [filepath],
                        verbosity=0,
                        permissive=True,
                        external=True,
                    )

                    ok: bool = not p.returncode
                    status: str = "🟢" if ok else "🔴"

                    with y.temp_width(60):
                        y.println(f"┌── • {filename.upper()} •")

                        if p.stdout:
                            # ... Raw to file
                            with open(f"{sub_root}/log__{filename}.txt", "w") as file:
                                file.write(p.stdout)
                            # ... Beautify to console
                            y.println("│  ")
                            for line in p.stdout.strip("\n").split("\n"):
                                y.println(f"│  {line}")

                        y.println("│  ")
                        y.print_fill("└{s}▸ {m}" "\n", "─", m=status)


################################################################################
### Tests
################################################################################


def tests(target_name: str = "all"):
    target_name, target_name_print = norm_target_name(target_name)
    y.print_header(f"TESTING{target_name_print}", post="")

    tests_dir: str = os.path.abspath(f"{BUILD_DIR}/tests")
    y.required_folder(tests_dir, info="Test(s) not executed.")

    tests_total: int = 0
    tests_passed: int = 0

    for root, _, files in os.walk(tests_dir):
        for filename in files:
            if target_name and filename != target_name:
                continue
            filepath: str = f"{root}/{filename}"

            if not y.file_is_binary(filepath):
                continue

            y.println()

            tests_total += 1
            p: y.RunCmdInfo = y.run_cmd(
                [filepath],
                verbosity=0,
                permissive=True,
                external=True,
            )
            ok: bool = not p.returncode
            status: str = "PASSED 🟢" if ok else "FAILED 🔴"

            with y.temp_width(60):
                y.println(f"┌── • {filename.upper()} •")

                if p.stdout:
                    # ... Raw to file
                    with open(f"{root}/log__{filename}.txt", "w") as file:
                        file.write(p.stdout)
                    # ... Beautify to console
                    y.println("│  ")
                    for line in p.stdout.strip("\n").split("\n"):
                        y.println(f"│  {line}")

                y.println("│  ")
                y.print_fill("└{s}▸ {m}" "\n", "─", m=status)

                tests_passed += int(ok)

    status: str = "PASS ✅️" if (tests_passed == tests_total) else "FAIL ⛔️"

    y.println()
    y.log_info(f"Passed tests ({tests_passed}/{tests_total}) ❱ {status}")


################################################################################
### Main
################################################################################


def main():

    #! Setup

    y.setup(show_traceback=True)

    #! Args

    parser = argparse.ArgumentParser(description="y-cpp project manager companion")
    subparsers = parser.add_subparsers(dest="command", required=True)
    parser.suggest_on_error = True

    # Common options
    parser.add_argument("-c", "--clean", action="store_true", help="Cleanup projects/tests from build dir")
    parser.add_argument("-f", "--fresh", action="store_true", help="Cleanup whole build dir")
    parser.add_argument("-d", "--debug", action="store_true", help="Build in Debug mode")
    parser.add_argument("-g", "--generator", type=str, default="Ninja", help="CMake generator")

    # Command: build
    build_parser = subparsers.add_parser("build", help="Config + Build a target")
    build_parser.add_argument("-i", "--interactive", action="store_true", help="Let you choose what to build")

    # Command: test
    test_parser = subparsers.add_parser("test", help="Run test(s)")
    test_parser.add_argument("-i", "--interactive", action="store_true", help="Let you choose what to test")

    # Command: run
    run_parser = subparsers.add_parser("run", help="Run a project")
    run_parser.add_argument("-i", "--interactive", action="store_true", help="Let you choose what to run")

    # Command: add
    add_parser = subparsers.add_parser("add", help="Add a project")
    add_parser.add_argument("project_name", type=str, help="Project name")

    # Parse args
    args = parser.parse_args()

    #! Vars

    build_type: str = "Release" if not args.debug else "Debug"
    sub_build_dir: str = f"{y.script_path()}/{BUILD_DIR}/sub-build"
    generator: str = args.generator

    #! Required

    y.required_command("cmake")

    if generator == "Ninja":
        y.required_command("ninja")

    #! Cleanup

    if args.fresh and os.path.isdir(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)
    os.makedirs(BUILD_DIR, exist_ok=True)

    if args.clean and os.path.isdir(sub_build_dir):
        shutil.rmtree(sub_build_dir)
    os.makedirs(sub_build_dir, exist_ok=True)

    #! Add

    # if args.command == "add":
    #     add()
    #     return

    #! Valid command ?

    if not args.command in ["build", "test", "run"]:
        return

    #! Config

    build_tests = args.command == "test"
    config(sub_build_dir, build_type, generator, build_tests=build_tests)

    #! Interactive layer

    user_choice = "all"

    targets = cmake_user_targets(sub_build_dir)
    targets = targets.tests if build_tests else targets.binaries

    if args.interactive:
        options = ["all", *targets] if build_tests else targets
        target_type = "test" if build_tests else "bin"
        user_choice = y.menu(options, f"Choose a {target_type} target to build", prompt="Build", starts_at=0)
        if not user_choice:
            y.error_exit("Invalid target to build")

    #! Build and Run

    build(sub_build_dir, build_type, target_name=user_choice)

    if args.command == "run":
        run(target_name=user_choice)

    if args.command == "test":
        tests(target_name=user_choice)


################################################################################
### Entry Point
################################################################################

y.entrypoint(main)
